---
site_name: Ansible Onboarding toolkit documentation
site_url: https://ansible.readthedocs.io/Onboarding toolkit
repo_url: https://github.com/ansible/Onboarding toolkit
edit_uri: blob/main/docs/
docs_dir: docs
strict: true

theme:
  name: "ansible"

nav:
  - index.md
  - onboarding_toolkit.md
  - docs_toolkit.md
  - contributing.md    


#see mkdocs for other optional extensions
